
services:
  app:
    image: node:20
    container_name: back_temperlam
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: sleep infinity

  db:
    image: postgres:18
    container_name: temperlam_db
    environment:
      POSTGRES_DB: temperlam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
